apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: gzmvayq7d-nodejs
  janus-idp.io/tekton: gzmvayq7d-nodejs
  backstage.io/kubernetes-id: gzmvayq7d-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: gzmvayq7d-nodejs
resources:
- deployment.yaml
- route.yaml
- service.yaml
